### ISSUE TITLE
Android geocoder still not working

### ISSUE THREAD

**Issue by vreixo** [CUTR-at-USF/OpenTripPlanner-for-Android#396] opened 2014-09-01 16:22 UTC
It seems that we are not getting back functionality automatically, I suppose that would be necessary to contact Google. 

Today Android geocoder results are still not working properly, just returning 4 or 5 too general results. For example selecting "Prefer Android geocoder" and Tampa server, writting "airport" on text boxes will display 4 results "Tampa, Pinellas County, Pinellas County Aquatic Preserve, Pasco County". And this are going to be the results for every input inserted on this server.

We still continue clearly limited.

At least Google Places is already working again.

**Comment by kalon33** [comment] 2015-11-05 14:45
Geocoding has stopped since a few days in the app (tested on both my phone and tablet). Any reason why?

**Comment by barbeau** [comment] 2015-11-05 15:03
@kalon33 Hmmm, not sure.  Doesn't seem to be working for me either in OTP Android.

Can you try running the below project on your device, and see if you get results when tapping the "Run Geocoder w/ bounding box" button?

https://github.com/barbeau/GeocoderDemo

**Comment by kalon33** [comment] 2015-11-06 14:53
@barbeau how can I build an apk from this to push on my phone/tablet? I launched gradle, it built properly but I cannot find the output file.

**Comment by barbeau** [comment] 2015-11-06 15:10
If you do `gradlew installDebug` it should directly install the app to your device.  You can then manually tap on the app icon "GeocoderDemo" to launch it.  You can alternately launch via command line with `adb shell am start -n com.barbeaudev.geocoderdemo/.GeocoderDemo`.

**Comment by kalon33** [comment] 2015-11-07 01:56
So I just tried it on my phone and got results (12 "airports" and 4 "station" when I launched these requests, without bounding box I could get my address resolved). So... it's seems an app problem isn't it? Maybe a quota problem of some API? Or some change in something?

**Comment by barbeau** [comment] 2015-11-08 04:35
I had forgotten the full history of this issue - I believe we pulled the Android Geocoder from OTP Android when it stopped working, and as a result we're using a different geocoder by default now.  So this issue is likely with that geocoder.  I'll see if I can look into it next week.

**Comment by kalon33** [comment] 2015-11-19 21:39
barbeau, do you think it might be a request number limit of some API?

**Comment by barbeau** [comment] 2015-11-19 21:56
Looks like its something with the MapQuest Nomination API.  If I change the
default search provider to Google Places it works.  But of course you can't
do this, because you can't access settings :(.  You could switch if you
build the app yourself.

I think the quick fix for this is to re-enable the Android geocoder, which
seems to be working again.

barbeau, do you think it might be a request number limit of some API?

—
Reply to this email directly or view it on GitHub
<https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/396#issuecomment-158205879>
.

**Comment by bikeoid** [comment] 2016-01-07 00:14
Mapquest has activated a developer key requirement for Nominatim,etc use during the 4th quarter of last year.   But it's limited to 15,000 transactions per month.
https://developer.mapquest.com/plan_purchase/steps/business_edition/business_edition_free

  I haven't surveyed - does everyone who runs an OTP server also serve an address lookup service at the API  /otp/geocode?   That could be a solution.

**Comment by barbeau** [comment] 2016-01-07 03:06
Thanks @bikeoid!  Good to know about MapQuest - just opened a new issue for that - https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/479.

Historically I believe the OTP geocoder has always been optional - you didn't have to deploy it with the webapp.  And, IIRC, the geocoder was actually ditched in more recent versions of OTP - I believe it no longer exists in the `master` branch.  At USF we're actually running two versions of OTP side-by-side to run the more recent master branch for main web client/server along with the older version that supports the geocoder.  If it re-emerges as a standard part of main OTP project I'm definitely open to adding that geocoder option.

So, the immediate path forward for us in OTP Android is to re-enable the Android geocoder (which IIRC is essentially reverting https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/pull/406 and https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/pull/408), and fixing MapQuest Nominatim (https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/479).

**Closed** 2016-01-08 17:29 UTC
Labels: bugs

**Comment by barbeau** [comment] 2016-01-08 18:01
Alright, both the Android and MapQuest geocoders should now be fixed.  I just pushed v2.1.4 to Google Play with these fixes, so it should be rolling out soon.  Please take a look when you get the update to make sure everything is working as intended.

Thanks to everyone for their patience dealing with these bugs!

**Comment by bikeoid** [comment] 2016-01-08 19:06
It worked here.   Thanks!

**Comment by afotest** [comment] 2016-07-08 10:20
When i use geocode in android device so in that case some device in properly work or some device in not work, Tell me about my device i am using Lenovo vibe k4 note in that case geocode get Latitude and Long value get but not nevigate in next activity so how can i resolved it ?

Also GPS on then after not proper work so what i should do ?
